### ISSUE TITLE
Problem load map on basic example

### ISSUE THREAD

**Issue by cmbreki** [angular-ui/ui-leaflet#257]
Hello,
i'm trying to recreate the basic example but it seems that i can't load the map (see image).
I have include the following dependencies: 
-angular version 1.2.6
-leaflet 0.7.1
-angular-simple-logger
-ui-leaflet-1.0.0

I get errors reporting that "Failed to load resource: net::ERR_FILE_NOT_FOUND file://a.tile.openstreetmap.org/1/0/0.png" , "file://b.tile.openstreetmap.org/1/1/0.png " etc.

Could you give me any hints about what is going wrong? 
![error](https://cloud.githubusercontent.com/assets/13789153/15648608/504ad8c8-2674-11e6-9519-bf4e58bbeba7.png)

Thank you in advance.

**Comment by seadour** [comment]
Hi cmbreki,

Are you running the example HTML page through a webserver, or are you just testing the HTML page by opening it directly in your browser? (e.g. with a URL of something like file://users/cmbreki/desktop/leaflet-test/index.html)

I think this may be why it's not working for you, because ui-leaflet uses relative paths and assumes you are running on a web server. This is why the tile URLs in your console error messages are all pre-pended with "file://" -- the application is looking on your local file system for these tiles.

If this is the case, try spinning up a simple web server and testing your page through that instead. If you're on a Mac or Linux, you can open Terminal, `cd` to the folder where your index.html file is hosted, and type `python -m SimpleHTTPServer 8000`. Then, open your browser and go to `localhost:8000`.

**Comment by nmccready** [comment]
@cmbreki please respond if this helped.

**Comment by cmbreki** [comment]
Thank you very much.
That was the problem.
