### ISSUE TITLE
Merge 1.X branch resolved issues with master

### ISSUE THREAD

**Issue by elesdoar** [angular-ui/ui-leaflet#294]
Hi @nmccready  

I've tried to merge but I don't know that merge, please you try it.

**Comment by nmccready** [comment]
Yeah, this is going to be tough as hell, might be easier to cherry pick.

**Comment by ValentinH** [comment]
I haven't check this project for a few weeks and I just came back today after seeing the release of Leaflet 1.0. Now, I see that there is a leaflet-1.X branch on this repository that is released on NPM. Thus, it's not really clear what branch/package a user should use in order to integrate with Leaflet 1.0. 

I think it would be great to clarify this in the README because now it's quite misleading. Also as a contributor, on which branch should I submit a PR to fix a bug due to latest Leaflet?

Thanks by advance

**Comment by elesdoar** [comment]
I've started to work on this today, please check the project [Version 3.x](https://github.com/angular-ui/ui-leaflet/projects/1)

**Comment by ValentinH** [comment]
OK thanks.
Where should I submit the PR?

**Comment by elesdoar** [comment]
For leaflet 1.x compatibility on branch [leaflet-1.X](https://github.com/angular-ui/ui-leaflet/tree/leaflet-1.X)

**Comment by ValentinH** [comment]
Will do then :+1:
